# Generated by Django 6.1.1 on 2026-09-23 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('classification', models.CharField(blank=True, choices=[('spam', 'Spam'), ('not_spam', 'Not Spam')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('promotional', 'Promotional'), ('prize_reward', 'Prize/Reward'), ('financial', 'Financial'), ('suspicious_link', 'Suspicious Link'), ('personal_info_request', 'Personal Information Request'), ('otp_auth', 'OTP/Authentication'), ('normal', 'Normal Message'), ('other', 'Other')], max_length=30)),
                ('explanation', models.TextField(blank=True)),
                ('suspicious_indicators', models.JSONField(blank=True, default=list)),
                ('safety_suggestion', models.TextField(blank=True)),
                ('user_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
